# Generated by Django 5.0.2 on 2024-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.EmailField(max_length=10)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
