# Generated by Django 5.0.2 on 2024-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
