# Generated by Django 5.0.2 on 2024-05-03 06:49

import translate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_alter_stars_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[translate.models.validate_stars]),
        ),
    ]
